[package]
name = "csr"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../client" }

yew = { version = "0.20", features = ["csr"] } # csr is needed by both ssr and csr
wasm-logger = "0.2"
log = "0.4"

[features]
ssr = ["yew/hydration"]