version: '3.9'

name: meet-me-when

services:
  web:
    build: .
    ports:
      - 80:3000

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meet_me_when
    ports:
      - 5432:5432